addedd

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -16,6 +16,9 @@ jobs:
       ADMIN_USERNAME: "azureuser"
       ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
       RESOURCE_GROUP_NAME: "Network-latest-10"
+      NSG_NAME: "Network-NSG"
+      VNET_NAME: "Network-VNET"
+      PIP_NAME: "Network-PIP"
 
     steps:
       - name: Checkout code
@@ -35,26 +38,30 @@ jobs:
         working-directory: terraform
         run: terraform init
 
+      - name: Check if NSG exists in Azure
+        run: |
+          az network nsg show --name ${{ env.NSG_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ env.ARM_SUBSCRIPTION_ID }} &>/dev/null || echo "NSG not found"
+        continue-on-error: true
+
       # Import Network Security Group if it exists
       - name: Import Network Security Group into Terraform State
-        if: |
-          az network nsg show --name Network-NSG --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ env.ARM_SUBSCRIPTION_ID }} &>/dev/null
+        if: success() && steps.Check_if_NSG_exists_in_Azure.outputs.stdout != 'NSG not found'
         working-directory: terraform
-        run: terraform import azurerm_network_security_group.nsg "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/networkSecurityGroups/Network-NSG"
+        run: terraform import azurerm_network_security_group.nsg "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/networkSecurityGroups/${{ env.NSG_NAME }}"
 
       # Import Virtual Network if it exists
       - name: Import Virtual Network into Terraform State
         if: |
-          az network vnet show --name Network-VNET --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ env.ARM_SUBSCRIPTION_ID }} &>/dev/null
+          az network vnet show --name ${{ env.VNET_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ env.ARM_SUBSCRIPTION_ID }} &>/dev/null
         working-directory: terraform
-        run: terraform import azurerm_virtual_network.vnet "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/virtualNetworks/Network-VNET"
+        run: terraform import azurerm_virtual_network.vnet "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/virtualNetworks/${{ env.VNET_NAME }}"
 
       # Import Public IP if it exists
       - name: Import Public IP into Terraform State
         if: |
-          az network public-ip show --name Network-PIP --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ env.ARM_SUBSCRIPTION_ID }} &>/dev/null
+          az network public-ip show --name ${{ env.PIP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ env.ARM_SUBSCRIPTION_ID }} &>/dev/null
         working-directory: terraform
-        run: terraform import azurerm_public_ip.pip "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/publicIPAddresses/Network-PIP"
+        run: terraform import azurerm_public_ip.pip "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/providers/Microsoft.Network/publicIPAddresses/${{ env.PIP_NAME }}"
 
       - name: Apply Terraform Configuration
         working-directory: terraform
@@ -65,12 +72,3 @@ jobs:
         run: |
           terraform output
           terraform output -json
-
-      # Check if Network Security Group (NSG) exists in Azure
-      - name: Check if NSG exists in Azure
-        run: |
-          az network nsg show --name Network-NSG --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ env.ARM_SUBSCRIPTION_ID }} || echo "NSG not found"
-
-
-
-
